<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;

class MakeAdminModuleCommand extends Command
{
    protected $signature = 'make:admin-module {name : Module name in PascalCase (e.g. Invoice)}
                            {--group=4 : Menu group ID (default: 4 = SYSTEM)}
                            {--icon=fas fa-cube : FontAwesome icon class}';

    protected $description = 'Scaffold a new admin module: controller, view, route, menu SQL patch';

    public function handle(): int
    {
        $name = $this->argument('name');
        $groupId = $this->option('group');
        $icon = $this->option('icon');

        // Derive names
        $pascal = Str::studly($name);                   // Invoice
        $kebab = Str::kebab($name);                     // invoice
        $snake = Str::snake($name);                     // invoice
        $title = Str::headline($name);                  // Invoice
        $controllerName = "{$pascal}Controller";

        $this->info("Scaffolding module: {$title}");
        $this->info('');

        // ── 1. Controller ─────────────────────────────
        $controllerPath = app_path("Http/Controllers/Admin/{$controllerName}.php");
        if (file_exists($controllerPath)) {
            $this->warn("  Controller already exists: {$controllerName}.php — skipped");
        } else {
            $controllerContent = <<<PHP
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class {$controllerName} extends Controller
{
    public function index(Request \$request)
    {
        \$admin = \$request->attributes->get('admin');

        return view('admin.pages.{$kebab}.index', compact('admin'));
    }
}
PHP;
            file_put_contents($controllerPath, $controllerContent);
            $this->info("  Created: app/Http/Controllers/Admin/{$controllerName}.php");
        }

        // ── 2. View ───────────────────────────────────
        $viewDir = resource_path("views/admin/pages/{$kebab}");
        $viewPath = "{$viewDir}/index.blade.php";
        if (file_exists($viewPath)) {
            $this->warn("  View already exists: {$kebab}/index.blade.php — skipped");
        } else {
            if (!is_dir($viewDir)) {
                mkdir($viewDir, 0755, true);
            }
            $viewContent = <<<BLADE
@extends('admin.layouts.app')
@section('title', '{$title}')

@push('styles')
<style>
    .module-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; }
    .module-header h1 { font-size: 22px; font-weight: 700; color: #1e293b; }
    .module-card { background: #fff; border-radius: 12px; border: 1px solid #f1f5f9; padding: 24px; }
</style>
@endpush

@section('content')
<div class="module-header">
    <h1><i class="{$icon}" style="color:#64748b;margin-right:8px"></i> {$title}</h1>
</div>

<div class="module-card">
    <p style="color:#64748b">Module <strong>{$title}</strong> is ready. Start building here.</p>
</div>
@endsection
BLADE;
            file_put_contents($viewPath, $viewContent);
            $this->info("  Created: resources/views/admin/pages/{$kebab}/index.blade.php");
        }

        // ── 3. Route snippet ──────────────────────────
        $routeSnippet = "Route::get('{$kebab}', [\\App\\Http\\Controllers\\Admin\\{$controllerName}::class, 'index'])->name('admin.{$kebab}.index');";
        $this->info('');
        $this->info("  Add this to routes/admin.php (inside authenticated group):");
        $this->line("  {$routeSnippet}");

        // ── 4. SQL patch ──────────────────────────────
        $patchDir = base_path('database/patches');
        if (!is_dir($patchDir)) {
            mkdir($patchDir, 0755, true);
        }
        $date = now()->format('Y_m_d');
        $patchFile = "{$patchDir}/{$date}_add_{$snake}_module.sql";
        $sortOrder = 20; // high number so it goes at the end

        $sqlContent = <<<SQL
-- =============================================
-- Add {$title} module
-- Generated by: php artisan make:admin-module {$name}
-- =============================================

-- Add menu item
INSERT INTO `tbl_admin_menus`
    (`group_id`, `parent_id`, `level`, `title`, `icon`, `route_name`, `url`, `permission_key`, `sort_order`, `is_active`, `created_at`, `updated_at`)
VALUES
    ({$groupId}, NULL, 1, '{$title}', '{$icon}', 'admin.{$kebab}.index', NULL, '{$snake}', {$sortOrder}, 1, NOW(), NOW());

-- Clear sidebar cache
DELETE FROM `cache` WHERE `key` LIKE '%sidebar_menu%';

-- Changelog
INSERT INTO `tbl_changelog` (`app_type`, `version`, `title`, `details`, `technical_info`, `created_at`)
VALUES ('office', '0.0.0', 'New module: {$title}', 'Added {$title} module with controller, view, route, and menu entry.', '{"module": "{$snake}"}', NOW());
SQL;

        file_put_contents($patchFile, $sqlContent);
        $this->info("  Created: database/patches/{$date}_add_{$snake}_module.sql");

        // ── Summary ───────────────────────────────────
        $this->info('');
        $this->info('  Next steps:');
        $this->info("  1. Add the route to routes/admin.php");
        $this->info("  2. Run the SQL patch in Database Manager");
        $this->info("  3. Build your module in {$controllerName}.php");
        $this->info('');

        return 0;
    }
}
